import { RegisterUserDto } from '@/lib/types';
import { registerSchema } from '@/lib/validationSchemas';
import { NextResponse, NextRequest } from 'next/server';
import bcrypt from 'bcryptjs';
import { prisma } from '@/lib/prisma';
import { signIn } from '@/auth';

/**
 *  @method  POST
 *  @route   ~/api/users/register
 *  @desc    Create New User [(Register) (Sign Up) (انشاء حساب)]
 *  @access  public
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as RegisterUserDto;

    // ✅ Validate
    const validation = registerSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
      { message: validation.error.issues[0].message },
        { status: 400 }
      );
    }

    // ✅ Check if user exists
    const existingUser = await prisma.user.findFirst({
      where: {
        OR: [
          { email: body.email },
          { username: body.username },
        ],
      },
    });

    if (existingUser) {
      return NextResponse.json(
        { message: 'This user already registered' },
        { status: 400 }
      );
    }

    // ✅ Hash password
    const hashedPassword = await bcrypt.hash(body.password, 10);

    // ✅ Insert user (ID will be auto-generated by trigger)
    const newUser = await prisma.user.create({
      data: {
        username: body.username,
        email: body.email,
        password: hashedPassword,
        roleId: 216, // Default role for patients
        fullName: body.fullName || body.username,
        phone: body.phone || '',
        isActive: 1,
      },
    });

    const userResponse = {
      id: Number(newUser.userId),
      username: newUser.username,
      roleId: newUser.roleId,
    };

    // ✅ Create session using NextAuth
    await signIn('credentials', { redirect: false, email: body.email, password: body.password });

    return NextResponse.json(
      { ...userResponse, message: "Registered & Authenticated" },
      { status: 201 }
    );

  } catch (error) {
    console.error("REGISTER ERROR:", error);
    
    // Handle Prisma unique constraint errors
    if (error && typeof error === 'object' && 'code' in error) {
      if (error.code === 'P2002') {
        return NextResponse.json(
          { message: 'This user already registered' },
          { status: 400 }
        );
      }
    }
    
    return NextResponse.json(
      { message: 'internal server error' },
      { status: 500 }
    );
  }
}
